[package]
name = "raft-rs"
version = "0.1.0"
authors = ["Isitha Subasinghe <isubasinghe@student.unimelb.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
sled = "0.34.6"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
serde = {version = "1.0.119", features=["derive"] }
bytes = { version = "1.0.1", features = ["serde"] }
bincode = "1.3.1"
actix-net = "0.2.6"
actix-utils = "2.0.0"
actix-codec = "0.3.0"
actix-service = "1.0.6"
actix-rt = "1.1.1"
actix-server = "1.0.4"
tokio = {version = "1.0.2", features=["full"]}
tokio-util = {version = "0.6.1", features=["full"]}
tokio-io = "0.1.13"